[package]
name = "bevy-progressbar"
version = "0.3.0"
edition = "2021"
license-file = "LICENSE.md"
description = "Create multi sectons progressbars and use them in the bevy ui"
repository = "https://github.com/tecbeast42/bevy-progressbar"
readme = "README.md"
keywords = ["gamedev", "progressbar", "ui", "bevy_ui"]
categories = ["game-development"]
exclude = [
    ".github/*",
]

[dependencies]
bevy_app = "0.10.0"
bevy_asset = "0.10.0"
bevy_ecs = "0.10.0"
bevy_render = "0.10.0"
bevy_ui = "0.10.0"

[dev-dependencies]
bevy = "0.10.0"
